### ISSUE TITLE
Compile and make runnable Automata library

### ISSUE THREAD

**Issue by tfiedor** [VeriFIT/mata-comparison#10]
Currently, there are some source files of Automata library in the virtual machine. It needs to be brought up to date.

This should comprise of:

- [x] Try compiling it. Create `build.sh` script that will build the VATA and copy the runnable binaries to `$HOME/bin`
- [x] Either create new binaries for each problem we are benchmarking or remake the parser of `.emp` programs to support n-ary intersection (needed by bool_comb/intersect benchmark) and taking the `.emp` program as first argument.
- [x] Check compatibility with .mata format. Then either create parser or convert .mata to supported format.

**Comment by jurajsic** [comment]
For CADE [this repo (and branch)](https://github.com/jurajsic/Automata/tree/bool-comb-benchmarks-new-dot) was used. Should be able to read `.mata` format (bit-vectors), but probably expects final formula to be in negated form.

**Comment by tfiedor** [comment]
Repo moved to https://github.com/VeriFIT/Automata/tree/tacas24

**Comment by tfiedor** [comment]
Should be setup for most of the benchmarks. Might need some tweeking.
